### ISSUE TITLE
BPM clock does not store clock rate

### ISSUE THREAD

**Issue by martin-lueders** [antoniograzioli/Autodafe#11]
Ciao Antonio,

it seems that the BPM clock module does not store the speed in the jSon. When loading a patch with the module, it always falls back to 120 BPM. Would be great if you could fix that, as the module is otherwise very nice with the multiply and divide outputs.

Cheers,
Martin

**Comment by antoniograzioli** [comment]
Hi Martin,
i have already fixed this issue in the binary version published on my website www.autodafe.net
