### ISSUE TITLE
BPM Clock: output voltage (1 V) isn't enough

### ISSUE THREAD

**Issue by DomiKamu** [antoniograzioli/Autodafe#16]
Hi,

BPM Clock module sends 1 V (instead of 10 V) to any output, BTW it's not enough to trigger, for example, VCV's Pulse Matrix (8 and 16) step sequencer.

Most BPM Clock modules (from other developer) I've tested always send +10 V on each clock beat.
Please consider to fix it for next release. TIA.

Regards.
Dominique.

**Comment by antoniograzioli** [comment]
yeah, I know, it should be between 1 and 2  volts to be in the standard Eurorack Voltages, it's on my list

https://vcvrack.com/manual/VoltageStandards.html

**Comment by DomiKamu** [comment]
Thanks for reply (appreciated),

VCV's **PulseMatrix** needs more thank 2 V on CLOCK input to run (this sequencer needs external clock). By injecting **exactly 2.00 V** the sequencer never run.

The article also mentions this: Trigger sources should produce 5 to 10V with a duration of 1 millisecond. An easy way to do this is to use PulseGenerator from digital.hpp.

Maybe consider to ask more explanation (when you'll can do it) to Andrew.

**Comment by antoniograzioli** [comment]
yes, this has already been fixed in my code. 
I hope to release some bugfixes for the next Rack release...

**Comment by antoniograzioli** [comment]
Fixed in the last update released SUn 28th Download it from : https://vcvrack.com/plugins.html
