### ISSUE TITLE
Build error, missing "dsp.hpp" - newest Master Rack version

### ISSUE THREAD

**Issue by berniemarx84** [antoniograzioli/Autodafe#3]
c++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -DVERSION_dev -MMD -O3 -march=nocona -ffast-math -Wall -g -DARCH_MAC -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -o build/src/Autodafe.cpp.o src/Autodafe.cpp
src/Autodafe.cpp:3:10: fatal error: 'dsp.hpp' file not found
#include "dsp.hpp"
         ^
1 error generated.
make: *** [build/src/Autodafe.cpp.o] Error 1

this error occurs when running the make sequence after pulling the updated rep. I also tried doing a full clean and re-clone but the error still occurs. 

Regards,

Bernie

**Comment by antoniograzioli** [comment]
yeah, it is caused by a last minute edit @AndrewBelt  made in the code yesterday. I have fixed it but still didn't upload the sources...

**Comment by antoniograzioli** [comment]
I fixed it yesterday, it should be fine now...
