### ISSUE TITLE
Formant filter problem

### ISSUE THREAD

**Issue by martin-lueders** [antoniograzioli/Autodafe#4]
Ciao Antonio,

I just found an problem with the formant filter. I had one in operation, and attempted to increase the 'Q' by doubling it up, and feeding the signal through two in series.

In the moment I 'duplicated' the module through the Rack right-click menu, the filter went unstable and maxed out the signal. Whenever I took it out the of the signal path, the patch worked fine, when I patched it in, I just got a loud click and then nor more audio, until I take it out again. Initializing did not help.

Cheers,
Martin

**Comment by antoniograzioli** [comment]
mmm...Ok I think I know what it is. I'll try to reproduce and fix it....
thanks

**Comment by antoniograzioli** [comment]
Problem fixed, I want to publicly thank @martin-lueders for helping me correct this bug
