### ISSUE TITLE
[Req] Row / Column all on / off for 8x16 seq

### ISSUE THREAD

**Issue by PatchworkBoy** [antoniograzioli/Autodafe#6]
Hi Antonio - any chance in the future of all on / off with both button and trig inputs, by row & column for the 8x16 seq... or a performance-based variant thereof?

**Comment by antoniograzioli** [comment]
do you mean "all" 128 gates buttons or all by each row and/or column?

**Comment by PatchworkBoy** [comment]
as in all in that row / all in that column... If I needed the effect of all 128 on or off I’d just set column 1 to on (or off) and step to 1.
